module.exports = {
  port: 7890,
  socksPort: 7891,
  redirPort: 7892,
  mixedPort: 7893,
  tproxyPort: 7894,

  allowLan: true,
  bindAddress: '*',
  ipv6: false,
  mode: 'rule',

  externalUI: 'ui',
  externalUIName: 'zashboard',
  externalUIURL: 'https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip',
  externalController: '0.0.0.0:9090',
  secret: '851119',
  authentication: [
    {
      user: 'nikki',
      pass: '851119',
    },
  ],

  geodataMode: true,
  geodataLoader: 'standard',
  geoAutoUpdate: true,
  geoUpdateInterval: 24,
  geoxURL: {
    geoip: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat',
    geosite: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat',
    mmdb: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb',
  },

  profile: {
    storeSelected: true,
    storeFakeIP: true,
    initialStartDelay: 20,
    periodicUpdateInterval: 48,
  },

  logLevel: 'warning',
  unifiedDelay: true,
  tcpConcurrent: true,
  findProcessMode: 'off',

  tun: {
    enable: true,
    stack: 'mixed',
    device: 'nikki-tun',
    autoRoute: true,
    autoRedirect: true,
    autoDetectInterface: true,
    gso: true,
    gsoMaxSize: 65536,
    mtu: 1500,
    dnsHijack: ['any:53', 'tcp://any:53'],
  },

  sniffer: {
    enable: true,
    sniff: {
      HTTP: {
        ports: [80, '8080-8880'],
        overrideDestination: true,
      },
      TLS: {
        ports: [443, 8443],
        overrideDestination: true,
      },
      QUIC: {
        ports: [443, 8443],
      },
    },
    forceDomain: ['+.v2ex.com'],
    skipDomain: ['+.baidu.com'],
  },

  dns: {
    enable: true,
    listen: '0.0.0.0:1053',
    ipv6: false,
    respectRules: true,
    enhancedMode: 'fake-ip',
    fakeIPRange: '198.18.0.1/16',
    fakeIPFilterMode: 'blacklist',
    fakeIPFilter: [
      'rule-set:private_domain',
      'rule-set:cn_domain',
      'rule-set:cndirect',
      '+.msftconnecttest.com',
      '+.msftncsi.com',
      'time.*.com',
      '+.apple.com',
      '+.market.xiaomi.com',
      '+.lan',
      '+.local',
      '+.connectivitycheck.gstatic.com',
      '+.captive.apple.com',
    ],
    defaultNameserver: ['223.5.5.5', '119.29.29.29'],
    proxyServerNameserver: [
      'https://dns.alidns.com/dns-query',
      'https://doh.pub/dns-query',
    ],
    nameserver: ['223.5.5.5', '119.29.29.29'],
  },

  proxyGroups: [
    {
      name: '🚀 默认代理',
      type: 'select',
      proxies: ['🔀 自建故转', '♻️ CF联通优选', '🌐 全部节点', '直连'],
    },
    {
      name: '🔀 自建',
      type: 'select',
      includeAll: true,
      filter: 'RN',
    },
    {
      name: '🔀 自建故转',
      type: 'fallback',
      proxies: ['🔀 自建', '♻️ 美国自动'],
      url: 'https://www.gstatic.com/generate_204',
      interval: 30,
      timeout: 5000,
    },
    {
      name: '♻️ CF联通优选',
      type: 'fallback',
      includeAll: true,
      tolerance: 50,
      interval: 300,
      filter: '(CF|联通|优选)',
    },
    {
      name: '🐟 漏网之鱼',
      type: 'select',
      proxies: ['🚀 默认代理', '直连', '🔀 自建故转', '♻️ CF联通优选', '🌐 全部节点'],
    },

    // 业务策略组
    {
      name: '⏱️ Speedtest',
      type: 'select',
      proxies: ['直连', '🚀 默认代理', '🔀 自建故转', '♻️ CF联通优选', '🌐 全部节点'],
    },
    {
      name: '🤖 AI',
      type: 'select',
      proxies: [
        '🚀 默认代理',
        '🔀 自建故转',
        '♻️ CF联通优选',
        '🔯 香港故转',
        '🔯 台湾故转',
        '🔯 韩国故转',
        '🔯 日本故转',
        '🔯 狮城故转',
        '🔯 美国故转',
        '🌐 全部节点',
      ],
    },
    {
      name: '📹 YouTube',
      type: 'select',
      proxies: [
        '🚀 默认代理',
        '🔀 自建故转',
        '♻️ CF联通优选',
        '♻️ 香港自动',
        '♻️ 台湾自动',
        '♻️ 韩国自动',
        '♻️ 日本自动',
        '♻️ 狮城自动',
        '♻️ 美国自动',
        '🌐 全部节点',
      ],
    },
    {
      name: '🎵 Spotify',
      type: 'select',
      proxies: [
        '🚀 默认代理',
        '🔀 自建故转',
        '♻️ CF联通优选',
        '♻️ 香港自动',
        '♻️ 台湾自动',
        '♻️ 韩国自动',
        '♻️ 日本自动',
        '♻️ 狮城自动',
        '♻️ 美国自动',
        '🌐 全部节点',
      ],
    },
    {
      name: '🎥 NETFLIX',
      type: 'select',
      proxies: [
        '🚀 默认代理',
        '🔀 自建故转',
        '♻️ CF联通优选',
        '♻️ 香港自动',
        '♻️ 台湾自动',
        '♻️ 韩国自动',
        '♻️ 日本自动',
        '♻️ 狮城自动',
        '♻️ 美国自动',
        '🌐 全部节点',
      ],
    },
    {
      name: '🍀 Google',
      type: 'select',
      proxies: [
        '🚀 默认代理',
        '🔀 自建故转',
        '♻️ CF联通优选',
        '♻️ 香港自动',
        '♻️ 台湾自动',
        '♻️ 韩国自动',
        '♻️ 日本自动',
        '♻️ 狮城自动',
        '♻️ 美国自动',
        '🌐 全部节点',
      ],
    },
    {
      name: '👨🏿‍💻 GitHub',
      type: 'select',
      proxies: [
        '🚀 默认代理',
        '🔀 自建故转',
        '♻️ CF联通优选',
        '♻️ 香港自动',
        '♻️ 台湾自动',
        '♻️ 韩国自动',
        '♻️ 日本自动',
        '♻️ 狮城自动',
        '♻️ 美国自动',
        '🌐 全部节点',
      ],
    },
    {
      name: '📲 Telegram',
      type: 'select',
      proxies: [
        '🚀 默认代理',
        '🔀 自建故转',
        '♻️ CF联通优选',
        '♻️ 香港自动',
        '♻️ 台湾自动',
        '♻️ 韩国自动',
        '♻️ 日本自动',
        '♻️ 狮城自动',
        '♻️ 美国自动',
        '🌐 全部节点',
      ],
    },
    {
      name: '💴 Paypal',
      type: 'select',
      proxies: ['直连', '🚀 默认代理', '🔀 自建故转', '♻️ CF联通优选', '🌐 全部节点'],
    },
    {
      name: '🐬 OneDrive',
      type: 'select',
      proxies: ['直连', '🚀 默认代理', '🔀 自建故转', '♻️ CF联通优选', '🌐 全部节点'],
    },
    {
      name: '🪟 Microsoft',
      type: 'select',
      proxies: ['直连', '🚀 默认代理', '🔀 自建故转', '♻️ CF联通优选', '🌐 全部节点'],
    },

    // 区域自动测速分流
    {
      name: '♻️ 香港自动',
      type: 'url-test',
      includeAll: true,
      excludeType: 'direct',
      tolerance: 50,
      interval: 300,
      filter: '(?i)(🇭🇰|港|HK|HKG|Hong ?Kong)',
    },
    {
      name: '♻️ 台湾自动',
      type: 'url-test',
      includeAll: true,
      excludeType: 'direct',
      tolerance: 50,
      interval: 300,
      filter: '(?i)(🇹🇼|台|TW|TWN|Taiwan)',
    },
    {
      name: '♻️ 韩国自动',
      type: 'url-test',
      includeAll: true,
      excludeType: 'direct',
      tolerance: 50,
      interval: 300,
      filter: '(?i)(🇰🇷|韩|KR|KOR|Korea)',
    },
    {
      name: '♻️ 日本自动',
      type: 'url-test',
      includeAll: true,
      excludeType: 'direct',
      tolerance: 50,
      interval: 300,
      filter: '(?i)(🇯🇵|日|JP|JPN|Japan)',
    },
    {
      name: '♻️ 狮城自动',
      type: 'url-test',
      includeAll: true,
      excludeType: 'direct',
      tolerance: 50,
      interval: 300,
      filter: '(?i)(🇸🇬|新加坡|狮城|SG|SGP|Singapore)',
    },
    {
      name: '♻️ 美国自动',
      type: 'url-test',
      includeAll: true,
      excludeType: 'direct',
      tolerance: 50,
      interval: 300,
      filter: '(?i)(🇺🇸|美|US|USA|United States|America)',
    },

    // 区域故障转移分流
    {
      name: '🔯 香港故转',
      type: 'fallback',
      includeAll: true,
      excludeType: 'direct',
      interval: 300,
      filter: '(?i)(🇭🇰|港|HK|HKG|Hong ?Kong)',
    },
    {
      name: '🔯 台湾故转',
      type: 'fallback',
      includeAll: true,
      excludeType: 'direct',
      interval: 300,
      filter: '(?i)(🇹🇼|台|TW|TWN|Taiwan)',
    },
    {
      name: '🔯 韩国故转',
      type: 'fallback',
      includeAll: true,
      excludeType: 'direct',
      interval: 300,
      filter: '(?i)(🇰🇷|韩|KR|KOR|Korea)',
    },
    {
      name: '🔯 日本故转',
      type: 'fallback',
      includeAll: true,
      excludeType: 'direct',
      interval: 300,
      filter: '(?i)(🇯🇵|日|JP|JPN|Japan)',
    },
    {
      name: '🔯 狮城故转',
      type: 'fallback',
      includeAll: true,
      excludeType: 'direct',
      interval: 300,
      filter: '(?i)(🇸🇬|新加坡|狮城|SG|SGP|Singapore)',
    },
    {
      name: '🔯 美国故转',
      type: 'fallback',
      includeAll: true,
      excludeType: 'direct',
      interval: 300,
      filter: '(?i)(🇺🇸|美|US|USA|United States|America)',
    },

    {
      name: '♻️ 自动选择',
      type: 'url-test',
      includeAll: true,
      tolerance: 50,
      interval: 300,
      filter:
        '^((?!(直连|剩余|套餐|官网|群|防失联|0.1倍|代理|鱼|自动|全部|故转|Speed)).)*$',
    },
    {
      name: '🌐 全部节点',
      type: 'select',
      includeAll: true,
      tolerance: 50,
      interval: 300,
      filter:
        '^((?!(直连|剩余|套餐|官网|群|防失联|0.1倍|代理|鱼|自动|全部|故转|Speed)).)*$',
    },
  ],

  rules: [
    { type: 'DOMAIN-SUFFIX', payload: 'amp-api-search-edge.apps.apple.com', policy: '直连' },
    { type: 'DOMAIN-SUFFIX', payload: 'amp-api-edge.apps.apple.com', policy: '直连' },
    { type: 'DOMAIN-SUFFIX', payload: 'amp-api.apps.apple.com', policy: '直连' },
    { type: 'DOMAIN-SUFFIX', payload: 'apps.apple.com', policy: '直连' },
    { type: 'DOMAIN-SUFFIX', payload: 'itunes.apple.com', policy: '直连' },
    { type: 'DOMAIN-SUFFIX', payload: 'mzstatic.com', policy: '直连' },
    { type: 'RULE-SET', payload: 'apple_domain', policy: '直连' },

    { type: 'RULE-SET', payload: 'cndirect', policy: '直连' },
    { type: 'RULE-SET', payload: 'gemini_domain', policy: '🤖 AI' },
    { type: 'RULE-SET', payload: 'ai', policy: '🤖 AI' },
    { type: 'RULE-SET', payload: 'speedtest_domain', policy: '⏱️ Speedtest' },
    { type: 'RULE-SET', payload: 'youtube_domain', policy: '📹 YouTube' },
    { type: 'RULE-SET', payload: 'spotify_domain', policy: '🎵 Spotify' },
    { type: 'RULE-SET', payload: 'netflix_domain', policy: '🎥 NETFLIX' },
    { type: 'RULE-SET', payload: 'netflix_ip', policy: '🎥 NETFLIX', noResolve: true },
    { type: 'RULE-SET', payload: 'google_domain', policy: '🍀 Google' },
    { type: 'RULE-SET', payload: 'google_ip', policy: '🍀 Google', noResolve: true },
    { type: 'RULE-SET', payload: 'github_domain', policy: '👨🏿‍💻 GitHub' },
    { type: 'RULE-SET', payload: 'telegram_domain', policy: '📲 Telegram' },
    { type: 'RULE-SET', payload: 'telegram_ip', policy: '📲 Telegram', noResolve: true },
    { type: 'RULE-SET', payload: 'paypal_domain', policy: '💴 Paypal' },
    { type: 'RULE-SET', payload: 'onedrive_domain', policy: '🐬 OneDrive' },
    { type: 'RULE-SET', payload: 'microsoft_domain', policy: '🪟 Microsoft' },
    { type: 'RULE-SET', payload: 'proxylist', policy: '🚀 默认代理' },
    { type: 'RULE-SET', payload: 'geolocation-cn', policy: '直连' },
    { type: 'RULE-SET', payload: 'private_domain', policy: '直连' },
    { type: 'RULE-SET', payload: 'private_ip', policy: '直连', noResolve: true },
    { type: 'RULE-SET', payload: 'cn_domain', policy: '直连' },
    { type: 'RULE-SET', payload: 'cn_ip', policy: '直连', noResolve: true },
    { type: 'MATCH', policy: '🐟 漏网之鱼' },
  ],

  ruleProviders: {
    cndirect: {
      uri: 'https://raw.githubusercontent.com/mryuecn/1pastescript/refs/heads/main/CNdirect.list',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'text',
    },
    proxylist: {
      uri: 'https://raw.githubusercontent.com/mryuecn/1pastescript/refs/heads/main/proxylist.list',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'text',
    },
    speedtest_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    apple_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    youtube_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    spotify_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    netflix_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    netflix_ip: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'ipcidr',
      format: 'mrs',
    },
    gemini_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-gemini.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    ai: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    google_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    google_ip: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'ipcidr',
      format: 'mrs',
    },
    github_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    telegram_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    telegram_ip: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'ipcidr',
      format: 'mrs',
    },
    geolocation_cn: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-cn.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    paypal_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    onedrive_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    microsoft_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    cn_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    private_domain: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'domain',
      format: 'mrs',
    },
    private_ip: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'ipcidr',
      format: 'mrs',
    },
    cn_ip: {
      uri: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs',
      interval: 86400,
      type: 'http',
      behavior: 'ipcidr',
      format: 'mrs',
    },
  },
};
